### ISSUE TITLE
Fix "código de ativação"

### ISSUE THREAD

**Issue by MurkBRA** [cFos/l10n#12]
pwd_header = "Senha.";
pwd_subheader = "Cada licença requer uma senha única.";
pwd_password_info = "Por favor, insira a senha da sua licença no formato xxxx-xxxx-xxxx-xxxx.";
pwd_password = "Senha:";
pwd_invalid_password = "Senha inválida. Por favor, verifique o que digitou e tente novamente.";

sn_header = "Número de série";

sn_subheader = "Insira seu número de série e ative sua licença.";

sn_info = "Caso possua um número de série de 16 dígitos no formato xxxx-xxxx-xxxx-xxxx, por favor, saia deste diálogo e dê um duplo-clique na sua licença. Uma tela irá a parecer onde será possível inserir seu número de série.\n\nCaso possua um número de série de 30 dígitos no formato xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx, por favor, insira-o agora para carregar e ativar sua licença.\n\n";
sn_serial_number = "Número de série:";

sn_invalid_serial_number = "Número de série inválido. Por favor, verifique o que digitou e tente novamente.";
sn16_info = "Digite seu número de série de 16 dígitos, para receber a sua licença. Você precisa estar conectado à Internet.";

sn16_info = "Digite seu número de série de 16 dígitos, para receber a sua licença. Você precisa estar conectado à Internet.";

repwd_header = "Senha %?.";

repwd_subheader = "A senha precisa de ser reinserida.";

repwd_reg_to = "Devido as alterações na configuração do seu sistema, terá que reinserir a senha para o registo do %p:";

err_bad_signature = "Sua senha parece estar errada ou ser de uma licença diferente. Por favor, insira a senha correta para este arquivo de licença.";

**Comment by MurkBRA** [comment]
This label "sn_serial_number" don't displays all string.
sn_serial_number = "Número de série:";
Display only "Número de"

**Comment by Nanianmichaels** [comment]
If it's not possible to expand that display in the software, or perhaps until it is, maybe go with "Núm. Série"? It also probably affects the PT-PT translation/display, and the same fix is possible.

By the way, on repwd_subheader = "A senha precisa de ser reinserido.";, it looks like "reinserido" should read "reinserida", since it refers to "senha", which is female.

Same thing on err_bad_signature = "Sua senha parece estar errado ou ser de uma licença diferente. Por favor, insira a senha correta para este arquivo de licença.";, this time on "errado": since it refers to "senha", it should be "errada".

**Comment by MurkBRA** [comment]
@Nanianmichaels Nice. Already edit... Thank you.

**Comment by ArmorDarks** [comment]
Thanks for your input!

I've forwarded that issue to Martin. I will let you know when it will be fixed.

I will take care of merging your translation into our l10n files a bit later. Thanks a lot for your work!

**Comment by ArmorDarks** [comment]
Lars reported that issue should be fixed in next beta by giving a bit more space for that line in UI of software

**Comment by ArmorDarks** [comment]
That issue should be fixed by now. Can you check latest beta and confirm it please? http://www.cfos.de/en/beta/index.htm

**Comment by MurkBRA** [comment]
Yes, I can confirm, the bug was fixed.

**Comment by ArmorDarks** [comment]
great, thanks! Then we can close it :)
