### ISSUE TITLE
duplicate strings for id cfout_p1c

### ISSUE THREAD

**Issue by petercpg** [cFos/l10n#13]
In Line 761 & 762 of locales.website/1033-en.cfos.txt:

`cfout_p1c = "Not time-limited version for commercial users on request:";`
`cfout_p1c = "The current pre-release does not support attachment files for calendar events.";`

The use same string id so only latter was export into locale files.

**Comment by ArmorDarks** [comment]
Thanks for the report! I forwarded issue to responsible person.
