### ISSUE TITLE
Translation missing - hungarian

### ISSUE THREAD

**Issue by ChiliP** [cFos/l10n#4]
Options > Settings

--------------in preferences tab--------------
text in favour ping time, with the "off" text it sais in hungarian:
"Ki: a cFosSpeed a lehető legnagyobb sávszélességet próbálja elérni, viszont a pings enyhe rovására mehet."
should be
"Ki: a cFosSpeed a lehető legnagyobb sávszélességet próbálja elérni, viszont a ping enyhe rovására mehet."  -  only 1 character at the end of pings, nothing major

text:
   Phone skins
translation:
   Telefon felületek

text:
   No password set, HTTP access from remote is forbidden.
translation:
   Nincs jelszó beállítva, külső HTTP hozzáférés letiltva.

for the "password set, HTTP access from remote is accepted."
Jelszó beállítva, külső HTTP hozzáférés engedélyezett.

text on button:
   Set Server Password
translation:
   Szerver jelszó beállítása

text:
   Prioritize process in foreground window 
translation:
   Adjon prioritást a legfelül levő ablak folyamatainak

text:
   Automatically set the priority of the process in foreground window to high.
translation:
   Automatikusan állítsa az előtérben levő ablak folyamatainak a prioritását magasra.

-----------------adapter-info tab----------------------
the informations are in english

Version   >   Verzió
Windows name   >   Windows név
Windows Version   >   Windows verzió
Maximum Raw Send Speed   >   Maximum nyers küldési sebesség
Maximum Acked Send Speed   >   Maximum igazolt küldési sebesség
Maximum Receive Speed   >    Maximum fogadott sebesség
Minimum Delay   >   Minimum késedelem
Delay Variance   >   késedelem eltérés
Traffic Counting Method   >   Forgalom számolási módszer
adaptive   >   adaptív
Averager Time   >   Átlagos Idő
Total Raw Sent Volume   >    Teljes elküldött nyers adatmennyiség
Total Acked Sent Volume   >    Teljes elküldött igazolt adatmennyiség
Total Received Volume   >    Teljes fogadott adatmennyiség
Total Time Used   >   Teljes felhasznált idő
No   >   Nem
Yes   >   Igen
Maximum IP Length   >    Maximum IP hosszúság
Pings Sent   >   Elküldött Pingek
Pongs Received    >     Pings Received (misstranslation in english?)    >   Fogadott Pingek
Current Send Speed    >    Jelenlegi küldési sebesség
Send Delay   >    Küldési Késedelem
Receive Delay   >   Fogadási késedelem
Calibration Done 0% (Poor)    >    Kalibráció Kész  0%
Traffic Shaping Status    >    Forgalom irányítás státusza     
shaping is active   >   forgalom irányítás aktív

**Comment by ArmorDarks** [comment]
Hi

Thanks for your input!

All translations have been added (expect it to see in closest beta).

Regarding that line:

> for the "password set, HTTP access from remote is accepted."
> Jelszó beállítva, külső HTTP hozzáférés engedélyezett.

Original string has changed a bit, now it looks like this:

```
http_access_enabled = "Password set, HTTP access from remote is allowed.";
```

New translation should be like that? Is it correct?

```
http_access_enabled = "Jelszó beállítva, külső HTTP hozzáférés megengedett.";
```

> -----------------adapter-info tab----------------------
> the informations are in english
> 
> Version > Verzió
> Windows name > Windows név
> Windows Version > Windows verzió
> Maximum Raw Send Speed > Maximum nyers küldési sebesség
> Maximum Acked Send Speed > Maximum igazolt küldési sebesség
> Maximum Receive Speed > Maximum fogadott sebesség
> Minimum Delay > Minimum késedelem
> Delay Variance > késedelem eltérés
> Traffic Counting Method > Forgalom számolási módszer
> adaptive > adaptív
> Averager Time > Átlagos Idő
> Total Raw Sent Volume > Teljes elküldött nyers adatmennyiség
> Total Acked Sent Volume > Teljes elküldött igazolt adatmennyiség
> Total Received Volume > Teljes fogadott adatmennyiség
> Total Time Used > Teljes felhasznált idő
> No > Nem
> Yes > Igen
> Maximum IP Length > Maximum IP hosszúság
> Pings Sent > Elküldött Pingek
> Pongs Received > Pings Received (misstranslation in english?) > Fogadott Pingek
> Current Send Speed > Jelenlegi küldési sebesség
> Send Delay > Küldési Késedelem
> Receive Delay > Fogadási késedelem
> Calibration Done 0% (Poor) > Kalibráció Kész 0%
> Traffic Shaping Status > Forgalom irányítás státusza
> 
> shaping is active > forgalom irányítás aktív

thanks for translation, but, unfortunately, we do not translate adapter's info — it's better to keep it in English.

In future I strongly suggest to take strings from our [locales](https://github.com/cFos/l10n/tree/master/locales.software) or contact me, to avoid translation of unneeded parts.

**Comment by ArmorDarks** [comment]
Seems no life here anymore. If you'll have time for that issue once again — just drop a line here, and I will reopen it. Thanks.
