### ISSUE TITLE
suspected typos in locales.website/1033-en.cfos.txt

### ISSUE THREAD

**Issue by petercpg** [cFos/l10n#9]
It looks like there are some some typos needed to confirm:
<blockquote>conf_alipay_text_v2b = "1. Transfer to our PayPal account:";</blockquote>
This should be "<b>Alipay</b> account" instead of PayPal?
<blockquote>net_wmi_l1d = "TCP/UPD connection count";</blockquote>
This should be "TCP/<b>UDP</b>"?
<blockquote>ptest_info_p1 = "With our new speed checker, you can quickly test the speed of your Internet connection. You can perform upload and download speed tests, for example to verify, if your Internet speed matches the promised values. The Speed Test is designed to measure your available bandwidth as fast as possible. Don't be alarmed if the speed check doesn't match the exact values your ISP gave you. For example if you have a broadband speed of 16Mbit/s, 1% tolerance is already 160.000 bit/sec, which looks impressive but makes no big difference.";</blockquote>
For US English, comma should be used as thousands delimiter, i.e., <b>160,000</b> bit/sec.

**Comment by ArmorDarks** [comment]
Hi

Thanks for an input!

Seems like `conf_alipay_text_v2b` and `net_wmi_l1d` indeed have typos. Let me check it out.

> For US English, comma should be used as thousands delimiter, i.e., 160,000 bit/sec.

Decimals and different delimiters always drove me crazy :)

Seems that you are right:
http://en.wikipedia.org/wiki/Decimal_mark

Though, I'd go with space as more universal and understandable for most locales delimiter.

I need to hear Martin's opinion about it.

**Comment by ArmorDarks** [comment]
Thanks once again.

Can I ask you fix `conf_alipay_text_v2b` in zh-TW too?

Thanks in advance!

**Comment by petercpg** [comment]
@ArmorDarks It it already translated to 支付寶, as Alipay's Chinese name.
Ref: https://en.wikipedia.org/wiki/Alipay

**Comment by ArmorDarks** [comment]
Great, thanks!

Then I'm closing issue :)
